name: App CI

on:
  push:
    # Run on all branches
    branches:
      - '*'
    # Run only if files modified are not docs
    paths-ignore:
      - '*.md'
      - 'plopfile.js'
      - '.editorconfig'
      - '.gitignore'
      - '.prettierrc'
      - '.prettierignore'
      - 'eslint-config.js'
  pull_request:
    # Run on all branches
    branches:
      - main
    # Run only if files modified are not docs
    paths-ignore:
      - '*.md'
      - 'plopfile.js'
      - '.editorconfig'
      - '.gitignore'
      - '.prettierrc'
      - '.prettierignore'
      - 'eslint-config.js'

jobs:
  setup:
    name: Checkout and Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

  cacheDependencies:
    name: Cache Dependencies
    uses: ./.github/workflows/cache_deps.yml

  buildAndTest:
    needs: cacheDependencies
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies #in case invalid or no cache
      - run: npm install

      - name: 🔨 Build
        run: npm run build

      - name: 🧪 Test
        run: npm run test

  #     # Upload dist artifacts
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: dist
  #         path: dist/

  #     # Upload coverage artifacts
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage
  #         path: coverage/lcov.info

  # coverage:
  #   name: Coverage Analysis
  #   needs: buildAndTest
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Download coverage artifacts
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: coverage

  #     - name: 📈 Upload coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         files: lcov.info

  # deploy:
  #   name: Deploy
  #   # Deploy only for main branch
  #   if: github.ref == 'refs/heads/main'
  #   needs: buildAndTest
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   # Manual deployment
  #   # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/
  #   environment:
  #     name: pchmn.github.io/vite-react-ts-ghactions-template
  #     url: https://pchmn.github.io/vite-react-ts-ghactions-template/
  #   steps:
  #     # Download dist artifacts
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: dist
  #         path: dist/

  #     - name: 🚀 Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: dist
# inspirations from https://github.com/pchmn/vite-react-ts-ghactions-template/blob/main/.github/workflows/ci.yml
